#!/bin/bash

VER=1.3.11-pre2
NAME=bogatka-macvlan
DB_RW=pg-0
DB_RO=pg-0
IP="192.168.10.1/24"

docker stop $NAME
docker container rm $NAME

docker run -t -d \
  --init \
  --name $NAME \
  --hostname $NAME \
  --network bogatka-macvlan \
  --restart unless-stopped \
  --env DB_HOSTS_RW="$DB_RW" \
  --env DB_HOSTS_RO="$DB_RO" \
  --env RELEASE_COOKIE=bogatka_macvlan_nsg_stand \
  --env ETH0_STATIC_IP="$IP" \
  -v /etc/ssl/bogatka:/etc/ssl/bogatka:ro \
  -v /var/log/bogatka_$NAME:/var/log \
  -v /home/bogatka/opt/download:/opt/app/download \
  -v /etc/localtime:/etc/localtime:ro \
  --cap-add=NET_ADMIN \
  --device /dev/net/tun:/dev/net/tun \
  nsgru/bogatka:$VER
