#!/bin/sh

# Zabbix DB
docker run -t \
  --name zabbix-postgres-server \
  --network host \
  --restart unless-stopped \
  -e POSTGRES_USER="zabbix" \
  -e POSTGRES_PASSWORD="zabbix" \
  -e POSTGRES_DB="zabbix_pwd" \
  -v /var/lib/postgresql/docker/zabbix-bogatka/data:/var/lib/postgresql/data \
  -v /etc/localtime:/etc/localtime:ro \
  -d postgres:14.3-alpine

# Zabbix server
docker run -t \
  --name zabbix-server-pgsql \
  --network host \
  --restart unless-stopped \
  -e DB_SERVER_HOST="zabbix-postgres-server" \
  -e POSTGRES_USER="zabbix" \
  -e POSTGRES_PASSWORD="zabbix" \
  -e POSTGRES_DB="zabbix_pwd" \
  -v /etc/localtime:/etc/localtime:ro \
  -d zabbix/zabbix-server-pgsql:alpine-5.4-latest

# Zabbix WEB
docker run -t \
  --name zabbix-web-nginx-pgsql \
  --network host \
  --restart unless-stopped \
  -e DB_SERVER_HOST="zabbix-postgres-server" \
  -e POSTGRES_USER="zabbix" \
  -e POSTGRES_PASSWORD="zabbix" \
  -e POSTGRES_DB="zabbix_pwd" \
  -e ZBX_SERVER_NAME="Богатка" \
  -e PHP_TZ="Europe/Moscow" \
  -v /etc/ssl/bogatka:/etc/ssl/nginx:ro \
  -v /etc/localtime:/etc/localtime:ro \
  -d zabbix/zabbix-web-nginx-pgsql:alpine-5.4-latest
