#!/bin/bash

# Версия сервера Богатки
VER=1.3.11-pre3

# Имя сервера Богатки
NAME=bogatka-0

# Список БД для записи/чтения
DB_RW="localhost"

# Список БД только для чтения
DB_RO="localhost"

# Параметры для подключения к Zabbix
ZEU=""
ZAU=""
ZSH=""
ZSP=""

# Раскомментируйте следующие две строки, если надо удалять ранее запущенный контейнер.
docker stop $NAME
docker container rm $NAME


docker run -t \
  --init \
  --name $NAME \
  --hostname $NAME \
  --network host \
  --restart unless-stopped \
  -e DB_HOSTS_RW="$DB_RW" \
  -e DB_HOSTS_RO="$DB_RO" \
  -v /etc/ssl/bogatka:/etc/ssl/bogatka:ro \
  -v /var/log/bogatka_$NAME:/var/log \
  -v /home/bogatka/opt/download:/opt/app/download \
  -v /etc/localtime:/etc/localtime:ro \
  --cap-add=NET_ADMIN \
  --device /dev/net/tun:/dev/net/tun \
  -e ZBX_EXT_URL="$ZEU" \
  -e ZBX_API_URL="$ZAU" \
  -e ZBX_SND_HOST="$ZSH" \
  -e ZBX_SND_PORT=$ZSP \
  -d nsgru/bogatka:$VER

